# Generated by Django 3.1.2 on 2020-11-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=10)),
                ('year', models.IntegerField(max_length=4)),
                ('transmission', models.SmallIntegerField(choices=[(1, 'manual'), (2, 'automatic'), (3, 'robot')], max_length=1)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
    ]
